name: Build and Release KDT

# Controls when the action will run. 
on:
  push:
    #branches: [ master ]
    branches: [ bugfix/upload-get-sh ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_registry:
    name: Build and KDT and push image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Version
        run: |
          git fetch --prune --unshallow --tags
          echo GIT_TAG=$(git describe --tags --abbrev=0) >> $GITHUB_ENV 

      - name: Upload `get.sh`
        uses: nogsantos/scp-deploy@master
        with:
          src: ./get.sh
          remote: ${{ secrets.SSH_REMOTE }}
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
